### PR TITLE
add FPGA config for P0

### PR DESCRIPTION
**Pull request by lschmid**
add fpga version for P0. The updater does print an error message and will stop if someone tries to update one of this fpga vesions

### CODE REVIEW

**Comment by diemf** [comment]
lgtm

**Comment by weblucas** [comment]
What is P0, P1 and P2?

**Comment by lschmid** [comment]
P0 is a hardware version of the visensor. The exact version is: Vi-Sensor P0 V1.0.

**Comment by weblucas** [comment]
Good to know. My sensor is the V3.1, this means that it is a P2?

**Comment by lschmid** [comment]
Not exactly. The P0 is an independent hardware. Your Sensor is simple the Vi-Sensor.

**Pull request closed without merging**
